#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it.
# Requirements:
# The MySQL dump must contain all your MySQL databases
# The MySQL dump must be named `backup.sql`
# The MySQL dump file has to be compressed to a `tar.gz` archive
# This archive must have the following name format: `day-month-year.tar.gz`
# The user to connect to the MySQL database must be `root`
# The Bash script accepts one argument that is the password used to connect to the MySQL database

passwd="$1"
if [ -z "$passwd" ]
then
    echo "Usage: "$0" <mysql_password>"
    exit 1
fi

date=$(date "+%d-%m-%Y")
dumpfile="backup.sql"
archive_file="${date}.tar.gz"

sudo mysqldump -uroot -p"$passwd" --all-databases > "$dumpfile"
sudo tar -czvf "$archive_file" "$dumpfile"
