#!/usr/bin/env bash
# This code demonstrates the usage of loops with conditionals

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]; then
		echo "Hi"
		echo "Best School"
	else
		echo "Best School"
	fi
	((i++))
done
