#!/usr/bin/env bash
# Demonstrates the usage of bash's while loop with if conditionals

i=1
while [ $i -le 10 ]
do
	if [ $i  -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
