#!/usr/bin/env bash
# Fix a container so that Nginx is running as the nginx user
# Requirements:
# `nginx` must be running as nginx user
# `nginx` must be listening on all active IPs on port `8080`
# You cannot use `apt-get remove`

# Update Nginx configuration to run as the nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Update the default site configuration to listen on all active IPs on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

#give nginx user read and write permissions to conf file
chmod u+rw /etc/nginx/nginx.conf

# Restart nginx as nginx user
sudo -u nginx service nginx restart
