#!/usr/bin/env bash
# A bash script to reload gunicorn in a graceful way

# obtain Gunicorn PID
GUNICORN_PIDS=$(sudo pgrep "gunicorn")

# check if Gunicorn is running
if [ -z "$GUNICORN_PIDS" ]
then
    echo "Gunicorn is not running"
    exit 1
fi

echo "Restart Gunicorn..."

for pid in $GUNICORN_PIDS
do
    echo "killing process with pid $pid"
    sudo kill -HUP "$pid"
done

# Wait for a short duration to allow workers to finish ongoing requests
sleep 5

echo "Gunicorn restarted successfully"

